-- Seed: Dublin mock listings (host + availability)
-- Password for host: password123

WITH host AS (
  INSERT INTO users (
    email,
    password_hash,
    role,
    status,
    email_verified,
    terms_version,
    terms_accepted_at,
    privacy_version,
    privacy_accepted_at
  )
  VALUES (
    'dublin.host@example.com',
    '$2a$10$Wm5cWGFJC0nN8hUplOTRTuBjzn6arSb6z26LRd1poa8kAOHiUFCa2',
    'host',
    'active',
    true,
    '2026-01-10',
    now(),
    '2026-01-10',
    now()
  )
  ON CONFLICT (email) DO UPDATE
  SET role = 'host'
  RETURNING id
),
inserted_listings AS (
  INSERT INTO listings (
    title,
    address,
    price_per_day,
    availability_text,
    host_id,
    amenities,
    geom,
    status,
    rating,
    rating_count
  )
  SELECT * FROM (
    VALUES
      (
        'Temple Bar Secure Driveway',
        '10 Temple Bar, Dublin 2',
        18,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['cctv', 'lighting'],
        ST_SetSRID(ST_MakePoint(-6.2630, 53.3450), 4326),
        'approved',
        4.8,
        12
      ),
      (
        'Trinity College Courtyard Spot',
        'College Green, Dublin 2',
        22,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['covered', 'security'],
        ST_SetSRID(ST_MakePoint(-6.2546, 53.3438), 4326),
        'approved',
        4.9,
        21
      ),
      (
        'St Stephen''s Green Garage',
        'St Stephen''s Green, Dublin 2',
        25,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['covered', 'lighting'],
        ST_SetSRID(ST_MakePoint(-6.2591, 53.3382), 4326),
        'approved',
        4.7,
        9
      ),
      (
        'Dublin Castle Resident Bay',
        'Castle St, Dublin 2',
        16,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['cctv'],
        ST_SetSRID(ST_MakePoint(-6.2675, 53.3430), 4326),
        'approved',
        4.6,
        7
      ),
      (
        'Docklands Secure Lot',
        'Grand Canal Dock, Dublin 2',
        20,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['cctv', 'ev_charging'],
        ST_SetSRID(ST_MakePoint(-6.2419, 53.3498), 4326),
        'approved',
        4.8,
        15
      ),
      (
        'Phoenix Park Visitor Space',
        'Parkgate St, Dublin 8',
        14,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['lighting'],
        ST_SetSRID(ST_MakePoint(-6.3296, 53.3567), 4326),
        'approved',
        4.5,
        5
      ),
      (
        'Smithfield Courtyard Space',
        'Smithfield Square, Dublin 7',
        15,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['lighting'],
        ST_SetSRID(ST_MakePoint(-6.2794, 53.3487), 4326),
        'approved',
        4.6,
        8
      ),
      (
        'Heuston Station Side Bay',
        'St John''s Rd W, Dublin 8',
        17,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['cctv'],
        ST_SetSRID(ST_MakePoint(-6.2929, 53.3463), 4326),
        'approved',
        4.7,
        11
      ),
      (
        'IFSC Covered Spot',
        'Custom House Quay, Dublin 1',
        23,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['covered', 'security'],
        ST_SetSRID(ST_MakePoint(-6.2482, 53.3481), 4326),
        'approved',
        4.9,
        18
      ),
      (
        'Merrion Square Private Space',
        'Merrion Square, Dublin 2',
        21,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['cctv', 'lighting'],
        ST_SetSRID(ST_MakePoint(-6.2528, 53.3395), 4326),
        'approved',
        4.8,
        14
      ),
      (
        'Rathmines Residential Spot',
        'Rathmines Rd, Dublin 6',
        13,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['lighting'],
        ST_SetSRID(ST_MakePoint(-6.2646, 53.3215), 4326),
        'approved',
        4.4,
        6
      ),
      (
        'Ballsbridge Driveway',
        'Shelbourne Rd, Dublin 4',
        19,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['cctv'],
        ST_SetSRID(ST_MakePoint(-6.2337, 53.3331), 4326),
        'approved',
        4.6,
        10
      ),
      (
        'Grand Canal Street Lot',
        'Grand Canal St Upper, Dublin 2',
        18,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['lighting'],
        ST_SetSRID(ST_MakePoint(-6.2449, 53.3389), 4326),
        'approved',
        4.5,
        9
      ),
      (
        'O''Connell Street Bay',
        'O''Connell St Upper, Dublin 1',
        20,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['security'],
        ST_SetSRID(ST_MakePoint(-6.2603, 53.3498), 4326),
        'approved',
        4.7,
        16
      ),
      (
        'Parnell Square Garage',
        'Parnell Square W, Dublin 1',
        16,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['covered'],
        ST_SetSRID(ST_MakePoint(-6.2679, 53.3522), 4326),
        'approved',
        4.4,
        7
      ),
      (
        'Capel Street Secure Space',
        'Capel St, Dublin 1',
        17,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['cctv'],
        ST_SetSRID(ST_MakePoint(-6.2688, 53.3478), 4326),
        'approved',
        4.6,
        13
      ),
      (
        'George''s Street Courtyard',
        'South Great George''s St, Dublin 2',
        18,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['lighting'],
        ST_SetSRID(ST_MakePoint(-6.2621, 53.3404), 4326),
        'approved',
        4.7,
        12
      ),
      (
        'Pearse Station Lot',
        'Pearse St, Dublin 2',
        19,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['security', 'covered'],
        ST_SetSRID(ST_MakePoint(-6.2495, 53.3437), 4326),
        'approved',
        4.8,
        17
      ),
      (
        'Camden Street Driveway',
        'Camden St Lower, Dublin 2',
        15,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['lighting'],
        ST_SetSRID(ST_MakePoint(-6.2655, 53.3369), 4326),
        'approved',
        4.5,
        8
      ),
      (
        'Ranelagh Village Spot',
        'Ranelagh Rd, Dublin 6',
        14,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['lighting'],
        ST_SetSRID(ST_MakePoint(-6.2558, 53.3268), 4326),
        'approved',
        4.4,
        6
      ),
      (
        'Harold''s Cross Space',
        'Harold''s Cross Rd, Dublin 6W',
        12,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['lighting'],
        ST_SetSRID(ST_MakePoint(-6.2761, 53.3238), 4326),
        'approved',
        4.3,
        4
      ),
      (
        'Drumcondra Private Spot',
        'Drumcondra Rd Lower, Dublin 9',
        13,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['cctv'],
        ST_SetSRID(ST_MakePoint(-6.2572, 53.3692), 4326),
        'approved',
        4.4,
        5
      ),
      (
        'Phibsborough Garden Space',
        'Phibsborough Rd, Dublin 7',
        12,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['lighting'],
        ST_SetSRID(ST_MakePoint(-6.2756, 53.3602), 4326),
        'approved',
        4.3,
        3
      ),
      (
        'Clontarf Promenade Spot',
        'Clontarf Rd, Dublin 3',
        16,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['security'],
        ST_SetSRID(ST_MakePoint(-6.1947, 53.3629), 4326),
        'approved',
        4.6,
        9
      ),
      (
        'Sandymount Village Bay',
        'Sandymount Green, Dublin 4',
        17,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['lighting'],
        ST_SetSRID(ST_MakePoint(-6.2249, 53.3308), 4326),
        'approved',
        4.5,
        8
      ),
      (
        'Stoneybatter Lane Spot',
        'Stoneybatter, Dublin 7',
        13,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['cctv'],
        ST_SetSRID(ST_MakePoint(-6.2871, 53.3472), 4326),
        'approved',
        4.4,
        6
      ),
      (
        'Blackrock Village Space',
        'Main St, Blackrock, Dublin',
        18,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['covered'],
        ST_SetSRID(ST_MakePoint(-6.1821, 53.3015), 4326),
        'approved',
        4.6,
        10
      ),
      (
        'Dublin Zoo Entry Spot',
        'Phoenix Park, Dublin 8',
        15,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['lighting'],
        ST_SetSRID(ST_MakePoint(-6.3047, 53.3563), 4326),
        'approved',
        4.5,
        7
      ),
      (
        'Christchurch Secure Bay',
        'Christchurch Pl, Dublin 8',
        17,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['security'],
        ST_SetSRID(ST_MakePoint(-6.2711, 53.3434), 4326),
        'approved',
        4.6,
        9
      ),
      (
        'Dame Street Courtyard',
        'Dame St, Dublin 2',
        19,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['cctv', 'lighting'],
        ST_SetSRID(ST_MakePoint(-6.2626, 53.3441), 4326),
        'approved',
        4.7,
        12
      ),
      (
        'Grafton Street Alley Spot',
        'Grafton St, Dublin 2',
        21,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['cctv', 'lighting'],
        ST_SetSRID(ST_MakePoint(-6.2596, 53.3416), 4326),
        'approved',
        4.8,
        18
      ),
      (
        'North Wall Quay Spot',
        'North Wall Quay, Dublin 1',
        20,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['security'],
        ST_SetSRID(ST_MakePoint(-6.2388, 53.3493), 4326),
        'approved',
        4.6,
        9
      ),
      (
        'Spencer Dock Garage',
        'Spencer Dock, Dublin 1',
        22,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['covered', 'security'],
        ST_SetSRID(ST_MakePoint(-6.2360, 53.3530), 4326),
        'approved',
        4.7,
        11
      ),
      (
        'Mayor Street Lot',
        'Mayor St Lower, Dublin 1',
        19,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['lighting'],
        ST_SetSRID(ST_MakePoint(-6.2330, 53.3495), 4326),
        'approved',
        4.5,
        7
      ),
      (
        'Tara Street Secure Space',
        'Tara St, Dublin 2',
        19,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['cctv'],
        ST_SetSRID(ST_MakePoint(-6.2540, 53.3470), 4326),
        'approved',
        4.6,
        10
      ),
      (
        'Baggot Street Driveway',
        'Baggot St Lower, Dublin 2',
        18,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['lighting'],
        ST_SetSRID(ST_MakePoint(-6.2475, 53.3369), 4326),
        'approved',
        4.4,
        6
      ),
      (
        'Portobello Lane Spot',
        'Portobello Rd, Dublin 8',
        14,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['lighting'],
        ST_SetSRID(ST_MakePoint(-6.2689, 53.3353), 4326),
        'approved',
        4.3,
        5
      ),
      (
        'Kilmainham Gate Space',
        'Inchicore Rd, Dublin 8',
        15,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['security'],
        ST_SetSRID(ST_MakePoint(-6.3058, 53.3410), 4326),
        'approved',
        4.5,
        8
      ),
      (
        'Ringsend Marina Bay',
        'Ringsend Rd, Dublin 4',
        17,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['lighting'],
        ST_SetSRID(ST_MakePoint(-6.2305, 53.3428), 4326),
        'approved',
        4.4,
        6
      ),
      (
        'Grand Canal Square Spot',
        'Grand Canal Sq, Dublin 2',
        23,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['covered'],
        ST_SetSRID(ST_MakePoint(-6.2374, 53.3439), 4326),
        'approved',
        4.8,
        14
      ),
      (
        'Mountjoy Square Driveway',
        'Mountjoy Square, Dublin 1',
        15,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['lighting'],
        ST_SetSRID(ST_MakePoint(-6.2587, 53.3561), 4326),
        'approved',
        4.3,
        4
      ),
      (
        'Royal Canal Dock Spot',
        'Royal Canal, Dublin 7',
        14,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['lighting'],
        ST_SetSRID(ST_MakePoint(-6.2820, 53.3538), 4326),
        'approved',
        4.2,
        3
      ),
      (
        'Cabra Village Space',
        'Cabra Rd, Dublin 7',
        13,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['lighting'],
        ST_SetSRID(ST_MakePoint(-6.2914, 53.3650), 4326),
        'approved',
        4.2,
        4
      ),
      (
        'Fairview Park Bay',
        'Fairview Strand, Dublin 3',
        15,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['security'],
        ST_SetSRID(ST_MakePoint(-6.2271, 53.3633), 4326),
        'approved',
        4.4,
        6
      ),
      (
        'North Circular Spot',
        'North Circular Rd, Dublin 7',
        14,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['cctv'],
        ST_SetSRID(ST_MakePoint(-6.2799, 53.3617), 4326),
        'approved',
        4.3,
        5
      ),
      (
        'Leeson Street Garage',
        'Leeson St Upper, Dublin 2',
        20,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['covered', 'lighting'],
        ST_SetSRID(ST_MakePoint(-6.2516, 53.3340), 4326),
        'approved',
        4.7,
        11
      ),
      (
        'Fitzwilliam Square Spot',
        'Fitzwilliam Square, Dublin 2',
        21,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['security'],
        ST_SetSRID(ST_MakePoint(-6.2520, 53.3348), 4326),
        'approved',
        4.7,
        9
      ),
      (
        'Grangegorman Gate Space',
        'Grangegorman Lower, Dublin 7',
        13,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['lighting'],
        ST_SetSRID(ST_MakePoint(-6.2809, 53.3579), 4326),
        'approved',
        4.2,
        4
      ),
      (
        'Liffey Boardwalk Bay',
        'Aston Quay, Dublin 2',
        18,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['cctv'],
        ST_SetSRID(ST_MakePoint(-6.2609, 53.3457), 4326),
        'approved',
        4.6,
        8
      ),
      (
        'Kevin Street Courtyard',
        'Kevin St Lower, Dublin 8',
        14,
        '24/7 access',
        (SELECT id FROM host),
        ARRAY['lighting'],
        ST_SetSRID(ST_MakePoint(-6.2662, 53.3389), 4326),
        'approved',
        4.3,
        5
      )
  ) AS v(
    title,
    address,
    price_per_day,
    availability_text,
    host_id,
    amenities,
    geom,
    status,
    rating,
    rating_count
  )
  RETURNING id
)
INSERT INTO listing_availability (
  listing_id,
  kind,
  starts_at,
  ends_at,
  repeat_weekdays,
  repeat_until
)
SELECT
  id,
  'open',
  date_trunc('day', now()) + time '00:00',
  date_trunc('day', now()) + time '23:59',
  ARRAY[0,1,2,3,4,5,6],
  NULL
FROM inserted_listings;
